channels:
  - pytorch
  - defaults
dependencies:
  - nltk=3.3.0
  - numpy=1.15.2
  - pip=10.0.1
  - python=3.6.5
  - scipy=1.1.0
  - tensorboard=1.11.0
  - tensorflow=1.11.0
  - tqdm=4.26.0
  - pytorch=0.4.1
  - torchvision=0.2.1
  - pip:
    - astunparse==1.6.1
    - ipython==6.5.0
    - scikit-learn==0.20.0
    - tensorboardx==1.4
